### ISSUE TITLE
The arxiv paper?

### ISSUE THREAD

**Issue by Gatsby23** [JokerJohn/PALoc#1]

**Comment by Gatsby23** [comment]
您好，会先放出arxiv版本的论文吗？

**Comment by JokerJohn** [comment]
是，有比较好的结果了会放出来。

**Comment by chengwei0427** [comment]
@JokerJohn 你好，

看到arxiv已经有预印版本了，有code的release计划吗？

**Comment by JokerJohn** [comment]
> @JokerJohn 你好，
> 
> 看到arxiv已经有预印版本了，有code的release计划吗？

期刊录用后了会整理放出来。

**Comment by chengwei0427** [comment]
> > @JokerJohn 你好，
> > 看到arxiv已经有预印版本了，有code的release计划吗？
> 
> 期刊录用后了会整理放出来。

方便问一下，这个project是[Robust_LIO_Localization](https://github.com/JokerJohn/Robust_LIO_Localization)的最终版本吗？

**Comment by JokerJohn** [comment]
> > > @JokerJohn 你好，
> > > 看到arxiv已经有预印版本了，有code的release计划吗？
> > 
> > 
> > 期刊录用后了会整理放出来。
> 
> 方便问一下，这个project是[Robust_LIO_Localization](https://github.com/JokerJohn/Robust_LIO_Localization)的最终版本吗？

不是一个工作，这个是做GT的，不要求性能，Robust_LIO_Localization这个是做实时定位的。

**Comment by chengwei0427** [comment]
> > > > @JokerJohn 你好，
> > > > 看到arxiv已经有预印版本了，有code的release计划吗？
> > > 
> > > 
> > > 期刊录用后了会整理放出来。
> > 
> > 
> > 方便问一下，这个project是[Robust_LIO_Localization](https://github.com/JokerJohn/Robust_LIO_Localization)的最终版本吗？
> 
> 不是一个工作，这个是做GT的，不要求性能，Robust_LIO_Localization这个是做实时定位的。

感谢你的耐心回复，期待你的好消息！

**Comment by JokerJohn** [comment]
the arxiv paper is here [link](https://arxiv.org/abs/2401.17826)
