### ISSUE TITLE
关于程序运行会出现延迟现象

### ISSUE THREAD

**Issue by ElaineChen10** [JokerJohn/PALoc#11]
胡博您好，我在follow您的代码时出现了延迟的问题，开启终端rosbag play完一整个包后，rviz才开始缓慢显示，对于stairs_alpha.bag需要运行二十多分钟，请问这个是正常的吗？（可能是因为我目前配置的电脑性能不够？ 我目前配置在虚拟机上，无法调用显卡）

**Comment by JokerJohn** [comment]
@ElaineChen10 感觉不太正常。如果你想快点，你可以调整先验地图的下采样尺寸，比如设置为0.1-0.5m，我觉得精度差距不会太大。但速度会快很多。

**Comment by ElaineChen10** [comment]
> @ElaineChen10 感觉不太正常。如果你想快点，你可以调整先验地图的下采样尺寸，比如设置为0.1-0.5m，我觉得精度差距不会太大。但速度会快很多。

先验地图的下采样尺寸具体是调整哪个参数呀，我尝试着把useGlobalPrior设置为false之后确实不卡顿延迟了，应该是设备性能不够。

**Comment by JokerJohn** [comment]
@ElaineChen10  just see this [instruction](https://github.com/JokerJohn/PALoc/blob/main/Tutorial/loc.md), i add some notes.
