### ISSUE TITLE
数据包资源

### ISSUE THREAD

**Issue by noobth1nker** [JokerJohn/PALoc#13]
作者您好，您的工作非常的优秀，想请问一下您能否提供一下parkinglot_01.bag对应的map.pcd的下载方式？

**Comment by JokerJohn** [comment]
就是fusion portablev2数据集中的校园真值地图，[这里下载](https://fusionportable.github.io/dataset/fusionportable_v2_data/)
<img width="949" alt="image" src="https://github.com/user-attachments/assets/e6aa6555-48dd-4232-8a77-0bddcc07ef0f">

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/48b022c0-134d-47c7-91ab-2457adbc0424">

**Comment by noobth1nker** [comment]
> 就是fusion portablev2数据集中的校园真值地图，[这里下载](https://fusionportable.github.io/dataset/fusionportable_v2_data/) <img alt="image" width="949" src="https://private-user-images.githubusercontent.com/25702851/393495973-e6aa6555-48dd-4232-8a77-0bddcc07ef0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Nzc5MzMsIm5iZiI6MTczMzU3NzYzMywicGF0aCI6Ii8yNTcwMjg1MS8zOTM0OTU5NzMtZTZhYTY1NTUtNDhkZC00MjMyLThhNzctMGJkZGNjMDdlZjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDEzMjAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYzQyZmE5MjdlZDVhOTJmZDgwM2M0MTc2MjQ1MzliNjllZWU4YWRmNmRkMDhmYmZmOWEyYmY0YTk4NTcwNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uPIOLZmym2qxt8i5y_5MSGJ-m1Ok9G09XuDRnNVHKY4">
> 
> <img alt="image" width="1150" src="https://private-user-images.githubusercontent.com/25702851/393495902-48b022c0-134d-47c7-91ab-2457adbc0424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Nzc5MzMsIm5iZiI6MTczMzU3NzYzMywicGF0aCI6Ii8yNTcwMjg1MS8zOTM0OTU5MDItNDhiMDIyYzAtMTM0ZC00N2M3LTkxYWItMjQ1N2FkYmMwNDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDEzMjAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZGVlMGVhN2E1NjdkYzgzYjk3YmFiZmVjNDllY2RmYjdmYmI1ZjdmNjZiMjA2M2Q1ZDkyNDRlNDVhZGIwMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._F7YqWDvSe0YFyuhyiYwvPA4vEOlI1mbRb3hLl_FVvo">

**Comment by noobth1nker** [comment]
好的，非常感谢您！@JokerJohn
