### ISSUE TITLE
How to selected the least constraints dimension?

### ISSUE THREAD

**Issue by qpc001** [JokerJohn/PALoc#2]
![image](https://github.com/JokerJohn/PALoc/assets/31476516/2b6030c3-f094-491b-abcc-36dbc3f6eb37)

How to **restore** the degenerate dimension from Hessian matrix or its svd result? And which frame is base on? (World frame or Body frame ?)

**Comment by JokerJohn** [comment]
> ![image](https://user-images.githubusercontent.com/31476516/251527686-2b6030c3-f094-491b-abcc-36dbc3f6eb37.png)
> 
> How to **restore** the degenerate dimension from Hessian matrix or its svd result? And which frame is base on? (World frame or Body frame ?)


In most corridor/tunnel degeneration problems, x (the direction of the vehicle's head) is the primary degeneration direction. We focus on detecting the degeneration of the translation part, and our current approach is to quickly determine the main degeneration direction. This is done in two steps:

Referencing LOAM, during the first iteration, we analyze the eigenvalues and eigenvectors (formula), especially the ratio of eigenvalues in the three dimensions of translation. This method often results in missed detections.

For each associated point, we compare the absolute values of the Jacobian in the xyz dimensions. If the x direction is the largest, we consider that this point contributes the most to x. We then count the number of all associated points and record their respective dimensions, further determining the degeneration dimension.

Our experiments have shown that this is a simple and effective method.

**Comment by qpc001** [comment]
> > ![image](https://user-images.githubusercontent.com/31476516/251527686-2b6030c3-f094-491b-abcc-36dbc3f6eb37.png)
> > How to **restore** the degenerate dimension from Hessian matrix or its svd result? And which frame is base on? (World frame or Body frame ?)
> 
> In most corridor/tunnel degeneration problems, x (the direction of the vehicle's head) is the primary degeneration direction. We focus on detecting the degeneration of the translation part, and our current approach is to quickly determine the main degeneration direction. This is done in two steps:
> 
> Referencing LOAM, during the first iteration, we analyze the eigenvalues and eigenvectors (formula), especially the ratio of eigenvalues in the three dimensions of translation. This method often results in missed detections.
> 
> For each associated point, we compare the absolute values of the Jacobian in the xyz dimensions. If the x direction is the largest, we consider that this point contributes the most to x. We then count the number of all associated points and record their respective dimensions, further determining the degeneration dimension.
> 
> Our experiments have shown that this is a simple and effective method.

What if the car is turning in a long straight tunnel ?

**Comment by JokerJohn** [comment]
> > > ![image](https://user-images.githubusercontent.com/31476516/251527686-2b6030c3-f094-491b-abcc-36dbc3f6eb37.png)
> > > How to **restore** the degenerate dimension from Hessian matrix or its svd result? And which frame is base on? (World frame or Body frame ?)
> > 
> > 
> > In most corridor/tunnel degeneration problems, x (the direction of the vehicle's head) is the primary degeneration direction. We focus on detecting the degeneration of the translation part, and our current approach is to quickly determine the main degeneration direction. This is done in two steps:
> > Referencing LOAM, during the first iteration, we analyze the eigenvalues and eigenvectors (formula), especially the ratio of eigenvalues in the three dimensions of translation. This method often results in missed detections.
> > For each associated point, we compare the absolute values of the Jacobian in the xyz dimensions. If the x direction is the largest, we consider that this point contributes the most to x. We then count the number of all associated points and record their respective dimensions, further determining the degeneration dimension.
> > Our experiments have shown that this is a simple and effective method.
> 
> What if the car is turning in a long straight tunnel ?
Referring to the image below, during the turning in a long tunnel, the constraints in the three dimensions (x, y, z) are quite rich, and there is no degeneration. With the addition of map constraints, the cumulative error brought by LIO and IMU factor constraints during the long tunnel period will be quickly corrected. Please see the attached image for a visual representation
<img width="714" alt="image" src="https://github.com/JokerJohn/PALoc/assets/25702851/754d7bba-e513-493e-a846-16be990788ce">

**Comment by JokerJohn** [comment]
@qpc001 Here are some demo videos that may help you understand the proposed methods. [demo](https://www.bilibili.com/video/BV11V4y1a7Fd/?vd_source=e401a6e84f70e7b5a55ae7f976092e3e)

**Comment by wwtinwhu** [comment]
@JokerJohn 你好，方便留个邮箱吗？关于退化检测的问题想请教交流一下。
