### ISSUE TITLE
Inquiry about Code and Paper Release for PALoc

### ISSUE THREAD

**Issue by qiaozhijian** [JokerJohn/PALoc#4]
Hello,

I'm happy to find the PALoc repository on GitHub, and I must say, I'm thoroughly impressed with the approach your team has developed for generating high-fidelity, dense 6-DoF ground truth trajectories. The concept of enhancing the evaluation of SLAM under diverse environmental conditions seems particularly promising. I believe that the robustness in degenerate conditions and advanced uncertainty analysis are critically important features that can significantly benefit the SLAM research community.

Could you please share the anticipated timeline for when the code and the associated paper might be available? Many researchers and practitioners in the community, myself included, are looking forward to exploring your framework and potentially contributing to its development.

Thank you for your dedication to advancing SLAM technologies, and I am looking forward to your response.

**Comment by JokerJohn** [comment]
We aim to organize and release the code before April.
