### ISSUE TITLE
gtsam编译问题

### ISSUE THREAD

**Issue by WangWenda98** [JokerJohn/PALoc#7]
您好，抱歉打扰。我使用推荐的gtsam4.02，进行编译时，提示缺GncOptimizwe.h 头文件。
从新删除原有gtsam4.02，从新注册后，/usr/local/include,没有该头文件。
想再次请教一下，您gtsam版本

**Comment by JokerJohn** [comment]
@WangWenda98 不好意思，我记错了，我刚查看了系统，gtsam的版本是4.2.0
![image](https://github.com/user-attachments/assets/3daa32e1-8371-4656-b2ba-6755986f05b9)

**Comment by WangWenda98** [comment]
没事，谢谢了、

**Comment by WangWenda98** [comment]
你好，抱歉再次麻烦你，踩了不少坑。想向您质询一下源码编译环境的配置问题，比如open3d版本号、tbb版本号，pcl版本号，还有重力因子代码编译时，报错Vector类型歧义。
