### ISSUE TITLE
你好，抱歉再次麻烦你，踩了不少坑。想向您质询一下源码编译环境的配置问题，比如open3d版本号、tbb版本号，pcl版本号，还有重力因子代码编译时，报错Vector类型歧义。

### ISSUE THREAD

**Issue by WangWenda98** [JokerJohn/PALoc#8]
你好，抱歉再次麻烦你，踩了不少坑。想向您质询一下源码编译环境的配置问题，比如open3d版本号、tbb版本号，pcl版本号，还有重力因子代码编译时，报错Vector类型歧义。

_Originally posted by @WangWenda98 in https://github.com/JokerJohn/PALoc/issues/7#issuecomment-2360379543_

**Comment by JokerJohn** [comment]
@WangWenda98 Open3D 0.17.0，这个版本需要注意用0.14.0以上的，因为要用到它的一些新的API.   PCL和tbb都是ubuntu 20.04的默认，版本是1.10.0.  tbb版本2020？

**Comment by WangWenda98** [comment]
可能是我使用的ubantu18.04，换了很多库，谢谢您的指导，我在尝试一下

**Comment by WangWenda98** [comment]
以解决

**Comment by JokerJohn** [comment]
@WangWenda98  我们新增了docker，还修复了一个bug，跑不通的话可以看看

**Comment by WangWenda98** [comment]
![2024-11-27 17-01-39 的屏幕截图](https://github.com/user-attachments/assets/a5f9e027-77e3-4c22-a083-079b219c6755)

![2024-11-27 17-01-52 的屏幕截图](https://github.com/user-attachments/assets/4ded1552-ebf6-4a40-bb42-debb6181a7b1)
![2024-11-27 17-02-05 的屏幕截图](https://github.com/user-attachments/assets/6f37d449-f62e-44d0-a352-77bf56f131b0)

**Comment by WangWenda98** [comment]
胡博士你好，重力因子优化那块无法重写函数，不知道您遇到没有，我查过基类虚函数签名好像没问题，很迷，期待您的回答。

**Comment by ljy-zju** [comment]
> @WangWenda98 Open3D 0.17.0，这个版本需要注意用0.14.0以上的，因为要用到它的一些新的API. PCL和tbb都是ubuntu 20.04的默认，版本是1.10.0. tbb版本2020？

麻烦胡博在主页更新一下，写的还是Open3D 0.11.0 以上，我装了个 0.13.0 的结果没有RegistrationGeneralizedICP 接口

**Comment by JokerJohn** [comment]
@ljy-zju 修复了
